vich_uploader:
    db_driver: orm

    mappings:
       profil:
           uri_prefix: /profil
           upload_destination: '%kernel.project_dir%/public/images/profil'


           inject_on_load: false;
           delete_on_update: true;
           delete_on_remove: true;